#!/bin/bash
# Environment variables for development

export ZOELIBRARYAPP_DB_HOST=""
export ZOELIBRARYAPP_DB_PORT="5432"
export ZOELIBRARYAPP_DB_NAME=""
export ZOELIBRARYAPP_DB_USER=""
export ZOELIBRARYAPP_DB_PASSWORD=""
export ZOELIBRARYAPP_FRONTEND_PORT=3002
export ZOELIBRARYAPP_BACKEND_PORT=5002
export ZOELIBRARYAPP_SECRET_KEY=""
#export ZOELIBRARYAPP_FLASK_ENV="development"
export ZOELIBRARYAPP_FLASK_ENV=""
export ZOELIBRARYAPP_AZURE_TENANT_ID=""
export ZOELIBRARYAPP_AZURE_CLIENT_ID=""
# export ZOELIBRARYAPP_AZURE_REQUIRED_GROUP_ID="your-group-id"
